version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - gosimple
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

# Remplacer exclude-rules par new syntax
exclude:
  - '.*_test.go:.*'    # Exclut les erreurs dans les fichiers *_test.go
