name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Next release version (SemVer, without v)"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      
      - name: Validate SemVer
        run: |
          if ! [[ "${{ inputs.version }}" =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$ ]]; then
            echo "Invalid SemVer version"
            exit 1
          fi

      - name: Ensure release branch does not already exist
        run: |
          if git ls-remote --exit-code --heads origin release/${{ inputs.version }}; then
            echo "Release branch already exists"
            exit 1
          fi

      - name: Version documentation (Docusaurus)
        run: |
          cd docs
          npm ci
          npx docusaurus docs:version ${{ inputs.version }}


      - name: Update CHANGELOG
        run: |
          VERSION="0.2.0"
          DATE="$(date +%Y-%m-%d)"

          awk -v version="$VERSION" -v date="$DATE" '
          BEGIN { in_unreleased = 0 }

          /^## \[Unreleased\]/ {
              print
              in_unreleased = 1
              buffer = ""
              next
          }

          /^## \[/ {
              if (in_unreleased) {
                  printf "\n### Added\n"
                  printf "\n### Fixed\n"
                  printf "\n### Changed\n"
                  printf "\n### Removed\n"
                  # End of Unreleased section, insert new version
                  printf "\n## [%s] - %s\n%s\n", version, date, buffer
                  in_unreleased = 0
              }
              print
              next
          }
                
          {
              if (in_unreleased) {
                  buffer = buffer $0 "\n"
              } else {
                  print
              }
          }

          END {
              if (in_unreleased) {
                  printf "\n## [%s] - %s\n%s\n", version, date, buffer
              }
          }
          ' CHANGELOG > CHANGELOG.tmp

          mv CHANGELOG.tmp CHANGELOG



      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore(release): ${{ inputs.version }}"
          title: "Release ${{ inputs.version }}"
          body: |
            Prepare release **${{ inputs.version }}**

            - Promotes `[Unreleased]` to `${{ inputs.version }}`
            - SemVer-compliant release
          base: ${{ github.event.repository.default_branch }}
          branch: release/${{ inputs.version }}

